# Generated by Django 5.1.4 on 2024-12-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='client',
        ),
    ]
