# Generated by Django 5.1.4 on 2024-12-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
        ('client', '0002_remove_address_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='basket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_basket', to='basket.basket'),
        ),
    ]
